import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#212134',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  titleContainer: {
    marginTop: 30,
    marginBottom: 10,
  },
  title: {
    color: '#fcfffe',
    fontSize: 40,
    fontFamily: 'Bevan-Regular',
  },
  playerChooser: {
    width: '60%',
    height: '10%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    margin: 10,
  },
  button: {
    flex: 1,
    borderColor: '#fefffe',
    borderWidth: 3,
    borderRadius: 8,
    margin: 10,
    height: '50%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonActive: {
    backgroundColor: '#feffff',
  },
  buttonText: {
    color: '#eff2f4',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'serif',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTextActive: {
    color: 'black',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'serif',
  },
  playerStatus: {
    backgroundColor: '#363652',
    width: '80%',
    height: '10%',
    margin: 10,
    borderRadius: 8,
    flexDirection: 'row',
  },
  playerStatusLeft: {
    width: '30%',
    height: '100%',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 10,
  },
  playerStatusRight: {
    backgroundColor: '',
    width: '70%',
    height: '100%',
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 10,
  },
  statusMainText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#f7f6f6',
  },
  playBoard: {
    backgroundColor: '#363652',
    width: 315,
    height: 315,
    borderRadius: 8,
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  grid: {
    width: '100%',
    height: '100%',
    margin: 8,
  },
  card: {
    backgroundColor: '#fefffe',
    padding: 10,
    margin: 5,
    borderRadius: 8,
    width: 90,
    height: 90,
    borderWidth: 1,
    borderColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footer: {
    backgroundColor: '#363652',
    borderRadius: 8,
    width: '80%',
    height: 60,
    margin: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerButton: {
    flex: 1,
    borderRadius: 8,
    margin: 5,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
  },
  resetButton: {
    backgroundColor: '#FF6F61',
  },
  startButton: {
    backgroundColor: '#4CAF50',
  },
  footerButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
});